/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalakiGame.BadConsequence;
import napakalakiGame.TreasureKind;

/**
 *
 * @author fran
 */
public class BadConsequenceView extends javax.swing.JPanel {

    BadConsequence bcView;

    public void setBadConsequence(BadConsequence bc) {
        bcView = bc;

        //Texto
        tfTexto.setText(bcView.getText());
        //Niveles perdidos
        tfNivel.setText(Integer.toString(bcView.getLevel()));
        //Numero de tosoros visibles perdidos
        tfNTV.setText(Integer.toString(bcView.getNVisibleTreasures()));
        //N tesoros ocultos perdidos
        tfNTH.setText(Integer.toString(bcView.getNHiddenTreasures()));
        //Tesoros visibles especificos
        //Comprobamos si hay algun tesoro que mostrar o no
        
        if (bc.getSpecificVisibleTreasures().isEmpty()) {
            this.visibles.setText("Nada");
        } else {
            for (TreasureKind t : bc.getSpecificHiddenTreasures()) {
                if(t == null){
                    this.visibles.setText("Nada");
                }else{
                    this.visibles.setText(t.toString());
                }
            }
        }
        
        if (bc.getSpecificHiddenTreasures().isEmpty()) {
            this.ocultosEspe.setText("Nada");
        } else {
            for (TreasureKind ta : bc.getSpecificHiddenTreasures()) {
                if(ta == null){
                    this.ocultosEspe.setText("Nada");
                }else{
                    this.ocultosEspe.setText(ta.toString());
                }
            }
        }
    }

    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTexto = new javax.swing.JLabel();
        tfNivel = new javax.swing.JLabel();
        tfNTV = new javax.swing.JLabel();
        tfNTH = new javax.swing.JLabel();
        visibles = new javax.swing.JLabel();
        ocultosEspe = new javax.swing.JLabel();

        jLabel1.setText("Texto");

        jLabel2.setText("Nivel perdido");

        jLabel3.setText("Tesoros visibles perdidos");

        jLabel4.setText("Tesoros ocultos perdidos");

        jLabel5.setText("Visibles especificos");

        jLabel6.setText("Ocultos especificos");

        tfTexto.setText("jLabel7");

        tfNivel.setText("jLabel7");

        tfNTV.setText("jLabel7");

        tfNTH.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfTexto))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNivel)
                    .addComponent(tfNTV)
                    .addComponent(tfNTH)
                    .addComponent(visibles)
                    .addComponent(ocultosEspe))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTexto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNivel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNTV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNTH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(visibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ocultosEspe)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel ocultosEspe;
    private javax.swing.JLabel tfNTH;
    private javax.swing.JLabel tfNTV;
    private javax.swing.JLabel tfNivel;
    private javax.swing.JLabel tfTexto;
    private javax.swing.JLabel visibles;
    // End of variables declaration//GEN-END:variables
}
