/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import napakalakiGame.CombatResult;
import napakalakiGame.Napakalaki;
import napakalakiGame.Player;
import napakalakiGame.Treasure;
/**
 *
 * @author fran
 */
public class PlayerView extends javax.swing.JPanel {
    
    Player playerModel;
    
    private Napakalaki napakalakiModel;
    
    public void fillTreasurePanel(JPanel aPanel, ArrayList<Treasure> aList){
        //Se elimina informacion antigua
        aPanel.removeAll();
        for(Treasure t : aList){
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure(t);
            aTreasureView.setVisible(true);
            aPanel.add(aTreasureView);
        }
        //Se fuerza la actualizacion visual del panel
        aPanel.repaint();
        aPanel.revalidate();
        
    }
    
    public void setPlayer(Player p){
        playerModel = p;
        
        //Nombre
        tfNombre.setText(playerModel.getName());
        //Bonus minimo
        tfNivel.setText(Integer.toString(playerModel.getLevel()));
        //Tesoros visibles
        fillTreasurePanel(panelTV, playerModel.getVisibleTreasures());
        //Tesoros ocultos
        fillTreasurePanel(panelTH, playerModel.getHiddenTreasures());
        
        nTesorosOcultos.setText(Integer.toString(playerModel.getHiddenTreasures().size()));
        nTesorosVisibles.setText(Integer.toString(playerModel.getVisibleTreasures().size()));
        repaint();
        revalidate();
    }
    
    public void setNapakalaki(Napakalaki n) {
        napakalakiModel = n; 
        repaint(); 
    }
    
    public ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
        // Se recorren los tesoros que contiene el panel,
        //    almacenando en un vector aquellos que están seleccionados.
        //    Finalmente se devuelve dicho vector.
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) {
           tv = (TreasureView) c;
           if ( tv.isSelected() )
              output.add ( tv.getTreasure() );
        }
        return output;
     }
    
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNivel = new javax.swing.JLabel();
        tfNombre = new javax.swing.JLabel();
        panelTH = new javax.swing.JPanel();
        comprarNivel = new javax.swing.JButton();
        hacerVisible = new javax.swing.JButton();
        descartaTesoros = new javax.swing.JButton();
        panelTV = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nTesorosOcultos = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nTesorosVisibles = new javax.swing.JLabel();

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Nivel: ");

        jLabel4.setText(" O");

        tfNivel.setText("jLabel9");

        tfNombre.setText("jLabel10");

        panelTH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        panelTH.setForeground(new java.awt.Color(77, 77, 77));

        comprarNivel.setText("Comprar nivel");
        comprarNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarNivelActionPerformed(evt);
            }
        });

        hacerVisible.setText("Hacer visible");
        hacerVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerVisibleActionPerformed(evt);
            }
        });

        descartaTesoros.setText("Descartar tesoros");
        descartaTesoros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartaTesorosActionPerformed(evt);
            }
        });

        panelTV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 7, 255)));

        jLabel5.setText("C");

        jLabel6.setText("U");

        jLabel7.setText("L");

        jLabel8.setText("T");

        jLabel9.setText(" O");

        jLabel10.setText("S");

        jLabel3.setText("V");

        jLabel11.setText("I ");

        jLabel12.setText("S");

        jLabel13.setText("I");

        jLabel14.setText("B");

        jLabel15.setText("L");

        jLabel16.setText("E");

        jLabel17.setText("S");

        jLabel18.setText("Total ocultos: ");

        nTesorosOcultos.setText("jLabel19");

        jLabel19.setText("Total visibles: ");

        nTesorosVisibles.setText("jLabel19");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNivel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(comprarNivel)
                                .addGap(18, 18, 18)
                                .addComponent(hacerVisible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descartaTesoros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTesorosVisibles))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(panelTH, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel17))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTV, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(nTesorosOcultos)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre)
                    .addComponent(jLabel2)
                    .addComponent(tfNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTH, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nTesorosOcultos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descartaTesoros)
                            .addComponent(hacerVisible)
                            .addComponent(comprarNivel)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelTV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nTesorosVisibles)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hacerVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerVisibleActionPerformed
        
        //a) Recopilar información de la GUI.
        
        ArrayList<Treasure> selHidden = getSelectedTreasures (panelTH);
        
        //b) Enviar mensajes al modelo para que se desarrolle la acción.
        napakalakiModel.makeTreasuresVisible(selHidden); 
        
        //c) Actualizar la vista.   
        setPlayer (napakalakiModel.getCurrentPlayer());
        
    }//GEN-LAST:event_hacerVisibleActionPerformed

    
    
    private void descartaTesorosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartaTesorosActionPerformed
        ArrayList<Treasure> selVisible = getSelectedTreasures(panelTV);
        ArrayList<Treasure> selHidden = getSelectedTreasures (panelTH);

        napakalakiModel.discardHiddenTreasures(selHidden);
        napakalakiModel.discardVisibleTreasures(selVisible);

        setPlayer (napakalakiModel.getCurrentPlayer());
        
        //panelTV.removeAll();
        
    }//GEN-LAST:event_descartaTesorosActionPerformed

    private void comprarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarNivelActionPerformed
      ArrayList<Treasure> selHidden = getSelectedTreasures(panelTH);
      ArrayList<Treasure> selVisible = getSelectedTreasures(panelTV);
        
      napakalakiModel.buyLevels(selVisible, selHidden);
        
      setPlayer(napakalakiModel.getCurrentPlayer());
      repaint(); 

    }//GEN-LAST:event_comprarNivelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprarNivel;
    private javax.swing.JButton descartaTesoros;
    private javax.swing.JButton hacerVisible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nTesorosOcultos;
    private javax.swing.JLabel nTesorosVisibles;
    private javax.swing.JPanel panelTH;
    private javax.swing.JPanel panelTV;
    private javax.swing.JLabel tfNivel;
    private javax.swing.JLabel tfNombre;
    // End of variables declaration//GEN-END:variables
}
