/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import napakalakiGame.Treasure;
/**
 *
 * @author fran
 */
public class TreasureView extends javax.swing.JPanel {
    Treasure treasureModel;
    
    private boolean selected = false;
    
    public void setTreasure(Treasure t){
        treasureModel = t;
        
        //Nombre
        tfNombre.setText(treasureModel.getName());
        //Bonus minimo
        tfBonusMin.setText(Integer.toString(treasureModel.getMinBonus()));
        //Bonus maximo
        tfBonusMax.setText(Integer.toString(treasureModel.getMaxBonus()));
        //Monedas
        coins.setText(Integer.toString(treasureModel.getGoldCoins()));
        //Tipo tesoro
        tfTipoTesoro.setText(treasureModel.getType().toString());
        repaint();
    }
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    public boolean isSelected(){
        return selected;
    }
    public Treasure getTreasure(){
        return treasureModel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTesoro = new javax.swing.JLabel();
        bonusMin = new javax.swing.JLabel();
        bonusMax = new javax.swing.JLabel();
        piezasOro = new javax.swing.JLabel();
        tipoTesoro = new javax.swing.JLabel();
        tfNombre = new javax.swing.JLabel();
        tfBonusMin = new javax.swing.JLabel();
        tfBonusMax = new javax.swing.JLabel();
        coins = new javax.swing.JLabel();
        tfTipoTesoro = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        nombreTesoro.setText("Nombre");

        bonusMin.setText("Bonus mínimo");

        bonusMax.setText("Bonus máximo");

        piezasOro.setText("Piezas de oro");

        tipoTesoro.setText("Tipo de tesoro");

        tfNombre.setText("   ");

        tfBonusMin.setText("   ");

        tfBonusMax.setText("   ");

        coins.setText("   ");

        tfTipoTesoro.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreTesoro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bonusMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfBonusMin)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bonusMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBonusMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoTesoro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTipoTesoro))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(piezasOro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coins)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coins)
                        .addComponent(nombreTesoro)
                        .addComponent(piezasOro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonusMax)
                    .addComponent(tfBonusMax)
                    .addComponent(tipoTesoro)
                    .addComponent(tfTipoTesoro)
                    .addComponent(bonusMin)
                    .addComponent(tfBonusMin)))
        );
    }// </editor-fold>//GEN-END:initComponents

    //si el tesoro ya estaba seleccionado (selected==true), deje de
    //estarlo; y si no estaba seleccionado pase a estar seleccionado.
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

            if(selected){
                selected = false;
                this.setBackground(null);
            }else{
                selected = true;
                this.setBackground(java.awt.Color.red);
                this.isSelected();
            }

        //Los cambios visuales se hacen efectivos
        repaint();
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonusMax;
    private javax.swing.JLabel bonusMin;
    private javax.swing.JLabel coins;
    private javax.swing.JLabel nombreTesoro;
    private javax.swing.JLabel piezasOro;
    private javax.swing.JLabel tfBonusMax;
    private javax.swing.JLabel tfBonusMin;
    private javax.swing.JLabel tfNombre;
    private javax.swing.JLabel tfTipoTesoro;
    private javax.swing.JLabel tipoTesoro;
    // End of variables declaration//GEN-END:variables
}
